name: bajik_app_monitoring_patient
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.0 # Use a more recent version of flutter_svg

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/l0g0.png
    - assets/images/logo.svg
    - assets/images/OnBoarding 1.svg
    - assets/images/OnBoarding 2.svg
    - assets/images/OnBoarding 3.svg
